### ISSUE TITLE
Overhaul

### ISSUE THREAD

**Issue by esalling23** [esalling23/changing-boston#21]
_this is a living document that will change as these suggestions are tested in development. all updates will be reflected here for documentation_

**Design**
- [ ] More than just black and white (choose color scheme)
- [ ] 8px padding and margin across all elements
- [ ] Set base font size to be 12px
  - [ ] Normal text will be 1 em
  - [ ] Header text will be 2.5 em
  - [ ] Button text will be .75 em and bold
- [ ] Create hover classes to be used across all elements (hover) and add transitions for smooth transformations
- [ ] Button design for all buttons

**Features and Polish**
- [ ] Error handling across the site
